### ISSUE TITLE
Wallpaper not updating

### ISSUE THREAD

**Issue by ShynizZ** [OhMyLob/Paper-Launcher#2]
When I change the wallpaper, I always need to kill the launcher to get the new wallpaper. 
Android 6.0.1, EUI 5.9.026S.

**Comment by matteolobello** [comment]
It seems that Android doesn't have a Broadcast Receiver for wallpaper change, I didn't give this "missing feature" much importance, actually.

**Comment by matteolobello** [comment]
Fixed
