### ISSUE TITLE
Customisation

### ISSUE THREAD

**Issue by ayan-das1234** [OhMyLob/Paper-Launcher#8]
I m not able to customise anything on my Android 6.0 device no icons for dock nothing

**Comment by edpratti** [comment]
Have you tried long pressing the wallpaper? That will bring up a dialog with the options.

**Comment by ayan-das1234** [comment]
@PrattiDev  I have tried that but still no effect, I am running it on Redmi Note 3 Kenzo

**Comment by matteolobello** [comment]
Wallpaper change fixed
